#! /usr/bin/python3

import os
import os.path
import sys


templatesPath = os.getenv("TEMPLATES_PATH")
cmakeTemplatesDir = '/CMake_templates/'
doxygenTemplatesDir = '/Doxygen_templates/'
sublimeTemplatesDir = '/Sublime_templates/'
tivaTemplatesDir = '/TivaC_templates/'


def deleteDir(directoryName):
	opt = input("Directory \'{}\' already exists, overwrite it? [Y/N]".format(directoryName))

	if opt == 'Y' or opt == 'y':

		for (dir, subdirs, files) in os.walk(directoryName, topdown=False):
			for f in files:
				filePath = os.path.join(dir, f)
				os.remove(filePath)

				if DEBUG:
					print("Removed file {}".format(p))

			os.rmdir(dir)

			if DEBUG:
				print("Removed dir {}".format(dir))
		
	else:
		print("Process cancelled.")
		sys.exit(0)


def createEntries(directoryName, category):
	
	os.mkdir(directoryName)
	os.chdir(directoryName)


	# create project structure
	os.mkdir('bin')
	os.mkdir('build')
	os.makedirs('docs/config')
	os.mkdir('include')
	os.mkdir('src')
	os.mkdir('lib')
	os.makedirs('test/bin')
	os.makedirs('test/build')
	

	# create README.md
	file = open('README.md', 'w')
	file.close()


	# initialize git repository for this project
	os.system("git init")


	# create .gitignore for git repository
	file = open('.gitignore', 'w')
	file.write("build/\n"
				"bin/\n"
				"*sublime*\n"
				"sftp-config.json\n")
	file.close()


	# copy CMakeList.txt template to project
	templateFile = templatesPath + cmakeTemplatesDir + category + "-CMakeLists.txt"
	os.system("cp {} {}".format(templateFile, 'CMakeLists.txt'))
	os.system("cp {} {}".format(templateFile, 'test/CMakeLists.txt'))


	# copy Doxygen configuration file to project with default name "Doxyfile"
	templateFile = templatesPath + doxygenTemplatesDir + "Doxyfile"
	os.system("cp {} {}".format(templateFile, "docs/config"))


	# copy sublime-project file to project
	templateFile = templatesPath + sublimeTemplatesDir + "x.sublime-project"
	os.system("cp {} {}.{}".format(templateFile, directoryName, "sublime-project"))

	# copy linker config file and startup file for TivaC project
	if category == "tiva":
		templateFile = templatesPath + tivaTemplatesDir + "linker_config.ld"
		os.system("cp {} .".format(templateFile))

		templateFile = templatesPath + tivaTemplatesDir + "startup_gcc.c"
		os.system("cp {} {}".format(templateFile, 'src'))

	print("Process finished successfully.")


DEBUG = False
	
if __name__ == "__main__":
	if len(sys.argv) == 1:
		directoryName = input("[Directory] ")
	else:
		directoryName = sys.argv[1]

	if templatesPath is None:
		print("Path to templates is not available.\n"
			">> Please add environment variable TEMPLATES_PATH='path/to/your/templates'")
		sys.exit(0)

	categories = [f.split('-')[0] for f in os.listdir(templatesPath + cmakeTemplatesDir)]

	text = "[Category]"
	for cat in categories:
		text += " " + cat

	category = input(text + ": ")
	if category not in categories:
		print("Category [{}] is not available".format(category))
		sys.exit(0)

	if os.path.exists(directoryName):
		deleteDir(directoryName)

	createEntries(directoryName, category)